version: '3'

services:
  telegram-bot:
    build: .
    restart: always
    volumes:
      # Mount only the users.json file as persistent storage
      - ./users.json:/app/users.json
      # Mount .env file for configuration
      - ./.env:/app/.env
    environment:
      - TZ=UTC  # Set timezone as needed 